// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");

function day1(input) {
  input.split("\n").map(Caml_format.caml_float_of_string);
  var solution = /* record */[/* contents */undefined];
  while(solution[0] === undefined) {
    solution[0] = 5;
    console.log(solution);
  };
  return /* () */0;
}

var input = "+1\n+2\n+3\n+4\n-5";

console.log(day1(input));

exports.day1 = day1;
exports.input = input;
/*  Not a pure module */
